<?php

function title_case_menu() {
  $items = array();
  $items['title_case'] = array(
    'title' => 'Title Case Generator',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('title_case_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['title_case_success_page'] = array(
    'title' => 'Success',
    'page callback' => 'title_case_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function title_case_form() {
  $form['phrase'] = array(
    '#title' => 'Your Phrase',
    '#type' => 'textfield',
    '#description' => t('Please enter the phrase you want to convert to.'),
  );

  $form['submit'] = array(
  '#type' => 'submit',
  '#value' => 'Convert',
  );

  return $form;
}

function title_case_form_submit($form, &$form_state) {
  $input_title = $form_state['values']['phrase'];

  $lowercase_words = strtolower($input_title);
  $new_array_of_words = explode(" ", $lowercase_words);
  $output_titlecased = array();
  $special_words = array("on", "the", "to", "from", "as");
  foreach ($new_array_of_words as $word) {
      if (in_array($word, $special_words) && $word != $new_array_of_words[0]) {
          array_push($output_titlecased, $word);
      } else {
          array_push($output_titlecased, ucfirst($word));
      }
  }
  $output_string = implode(" ", $output_titlecased);

  $_SESSION['title_case_output'] = $output_string;

  $form_state['redirect'] = 'title_case_success_page';
}

function title_case_success() {
  $output_title = $_SESSION['title_case_output'];
  return 'Your output is: <strong>' . $output_title . '</strong>';
}
